### ISSUE TITLE
Update README conform guidelines on grading page

### ISSUE THREAD

**Issue by rikverlaan** [course-dprep/Airbnb_Ratings_Bedroom_Analysis#65]

**Comment by vscanturk** [comment]
Started and initial made initial progress, 
we need to summarize method, variables:
we need to add necessary tables or charts 
we can add alternative routes to run the codes
we can add conclusion and interpretion about our analysis

**Comment by bram-teunissen** [comment]
@vscanturk is this completed yet?

**Comment by bram-teunissen** [comment]
done
